/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

class Problem2 {
    int solve(int number) {
        int sum = 2;

        int first = 1;
        int second = 2;
        int nextFibonacciTerm = 0;
        while (nextFibonacciTerm <= number) {
            nextFibonacciTerm = first + second;

            if (nextFibonacciTerm % 2 == 0) {
                sum += nextFibonacciTerm;
            }
            first = second;
            second = nextFibonacciTerm;
        }
        return sum;
    }
}
